# Enable Home Assistant API
api:
  encryption:
    key: "f29o8Z+EEDuZS1tCF1Tqi6exl1PefuCo9fxce99oeg0="

ota:
  - platform: esphome
    password: "7226b4fa8da5ba6a4275e8eca8feb975"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Crowpanel-7-Advance"
    password: "e0lnnIgp83Fr"

captive_portal:
    
substitutions:
  device_name: crowpanel-7-advance

external_components:
  - source: my_components
    components: [ pca9557 ]

esphome:
  name: ${device_name}
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
  # on_boot:
  #   - priority: 600
  #     then:
  #       - logger.log: "Scanning I2C bus"
  #       - i2c.scan:
  #           then:
  #             - logger.log: "I2C devices found: ${devices}"
  #   - priority: 500
  #     then:
  #       - logger.log: "Initializing touch first"
  #       - component.update: touch_gt911
    # - priority: -100
    #   then:
    #     - logger.log: "Initializing backlight"
    #     - output.turn_on: backlight_output

web_server:
  port: 80

font:
  - file: "fonts/arial.ttf"
    id: my_font
    size: 40
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz

logger:

# Define PWM output for backlight (ajusta el pin según tu hardware)
i2c:
  sda: 15
  scl: 16
  # scan removed to prevent interferencia con el touchscreen
  frequency: 400000

# Configure the GT911 touchscreen
touchscreen:
  platform: gt911
  id: touch_gt911
  address: 0x5D
  on_touch:
    then:
    - logger.log: "Detectando toque en la pantalla"

output:
  - platform: pca9557
    id: backlight_output
    address: 0x18

light:
  - platform: binary
    output: backlight_output
    name: ${device_name} Display Backlight
    id: back_light
    restore_mode: ALWAYS_ON

display:
  - platform: rpi_dpi_rgb
    id: my_display
    color_order: RGB  # Ajusta si los colores se ven incorrectos
    invert_colors: True
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 800
      height: 480
    de_pin: 42  # HEN en tu configuración original
    hsync_pin: 40  # HSYNC
    vsync_pin: 41  # VSYNC 
    pclk_pin: 39  # PCLK
    pclk_frequency: 12MHz  # Puedes ajustar esta frecuencia si es necesario
    data_pins:
      red:
        - 7   # R0
        - 17  # R1
        - 18  # R2
        - 3   # R3
        - 46  # R4
      green:
        - 9   # G0
        - 10  # G1
        - 11  # G2
        - 12  # G3
        - 13  # G4
        - 14  # G5
      blue:
        - 21  # D0/B0
        - 47  # D1/B1
        - 48  # D2/B2
        - 45  # D3/B3
        - 38  # D4/B4

     

# Resto de la configuración LVGL si deseas usarla
globals:
  - id: random_int_var
    type: int
    restore_value: no
    initial_value: '0'

binary_sensor:
  - platform: lvgl
    widget: button
    name: Button
    on_press:
      then:
        - lambda: |-
            id(random_int_var) = (rand() % 20) - 10;
        - lvgl.indicator.update:
            id: power_meter_input
            value: !lambda return id(random_int_var);
        - lvgl.label.update:
            id: power_kw
            text:
              format: "%dkW"
              args: [ 'id(random_int_var)' ]

image:
  - file: mdi:sun-wireless-outline
    id: solar_power_icon
    resize: 50x50

# Configuración LVGL (mantiene la misma)
lvgl:
  color_depth: 16
  bg_color: 0
  border_width: 0
  outline_width: 0
  shadow_width: 0
  text_font: unscii_16
  align: center
  style_definitions:
    - id: meter_style
      border_width: 0
      outline_width: 0
      align: center
      bg_color: 0
    - id: title_style
      text_font: MONTSERRAT_40
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
    - id: detail_style
      text_font: MONTSERRAT_18
      align: center
      text_color: 0xFFFFFF
      bg_opa: TRANSP
      bg_color: 0
      radius: 4
      pad_all: 2
  widgets:
    - button:
        id: button
        height: 100
        width: 200
        x: 20
        y: 20
        border_width: 0
        outline_width: 0
        align: TOP_LEFT
        checkable: false
        widgets:
        - label:
            align: center
            text: "Button"
    - obj:
        height: 240
        width: 240
        bg_color: 0
        border_width: 0
        outline_width: 0
        shadow_width: 0
        pad_all: 4
        align: TOP_MID
        widgets:
          - meter:
              height: 100%
              width: 100%
              border_width: 0
              outline_width: 0
              align: center
              bg_color: 0
              scales:
                angle_range: 180
                range_to: 10
                range_from: -10
                ticks:
                  count: 0
                indicators:
                  - line:
                      id: power_meter_input
                      width: 8
                      color: 0xFFFFFF
                      r_mod: 12
                      value: 50
                  - arc:
                      color: 0xFF3000
                      r_mod: 10
                      width: 20
                      start_value: -10
                      end_value: 0
                  - arc:
                      color: 0x00FF00
                      r_mod: 10
                      width: 20
                      start_value: 0
                      end_value: 10
          - arc:
              height: 160
              width: 160
              align: center
              arc_color: 0x000000
              arc_width: 150
              start_angle: 0
              end_angle: 360
              indicator:
                arc_width: 150
                arc_color: 0x000000
          - label:
              styles: detail_style
              y: 8
              x: -99
              text: "-10"
          - label:
              styles: detail_style
              y: 8
              x: 99
              text: "+10"
          - label:
              styles: title_style
              id: power_kw
              y: -10
          - image:
              src: solar_power_icon
              id: img_solar_power
              align: center
              image_recolor: 0xFFFF00
              image_recolor_opa: 100%
              y: 50