# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Crowpanel-7-Advance"
    password: "e0lnnIgp83Fr"

captive_portal:
    
substitutions:
  device_name: crowpanel-7-advance

esphome:
  name: ${device_name}
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

web_server:
  port: 80

font:
  - file: "fonts/arial.ttf"
    id: my_font
    size: 40
  
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
  variant: esp32s3

psram:
  mode: octal
  speed: 80MHz

# Añadido logging para debug
logger:
  level: DEBUG
  logs:
    touch: DEBUG
    display: DEBUG
i2c:
  sda: 15
  scl: 16
  frequency: 400000
  id: i2c_bus

# Backlight configuration
i2c_device:
  id: pca9557
  address: 0x18
  i2c_id: i2c_bus

output:
  - platform: template
    id: backlight_output
    type: binary
    write_action:
      - lambda: |-
          uint8_t config_reg = 0x03;
          uint8_t config_data = 0xFD;
          id(pca9557).write_byte(config_reg, config_data);
          delay(10);
          uint8_t output_reg = 0x01;
          uint8_t output_data = state ? 0x02 : 0x00;
          id(pca9557).write_byte(output_reg, output_data);

light:
  - platform: binary
    name: "Backlight"
    output: backlight_output
    id: backlight
    restore_mode: ALWAYS_ON

display:
  - platform: rpi_dpi_rgb
    id: my_display
    color_order: RGB
    invert_colors: true
    update_interval: 33ms
    auto_clear_enabled: false
    dimensions:
      width: 800
      height: 480
    de_pin: 42
    hsync_pin: 40
    vsync_pin: 41
    pclk_pin: 39
    pclk_frequency: 18MHz
    data_pins:
      red:
        - 7
        - 17
        - 18
        - 3
        - 46
      green:
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
      blue:
        - 21
        - 47
        - 48
        - 45
        - 38

touchscreen:
  platform: gt911
  id: touch_gt911
  address: 0x5D
  on_touch:
    then:
      - lambda: |-
          std::string coords = "Touch detected!";
          lv_label_set_text(id(touch_coords), coords.c_str());

globals:
  - id: counter
    type: int
    restore_value: no
    initial_value: '0'
  - id: display_text
    type: std::string
    restore_value: no
    initial_value: '"Hello World!"'

# [Previous configuration until lvgl section remains the same]

lvgl:
  color_depth: 16
  bg_color: 0x000000
  border_width: 0
 
  style_definitions:
    - id: button_style
      bg_color: 0x0000FF
      radius: 20
      border_width: 2
      border_color: 0xFFFFFF
      pad_all: 10
   
    - id: label_style
      text_font: MONTSERRAT_40
      text_color: 0xFFFFFF
      align: CENTER
      bg_opa: TRANSP
   
    - id: button_label_style
      text_font: MONTSERRAT_20
      text_color: 0xFFFFFF
      align: CENTER
      bg_opa: TRANSP
    
    - id: color_box_style
      width: 120
      height: 100  # Increased height to accommodate label
      radius: 10
      border_width: 1
      border_color: 0xFFFFFF

    - id: color_label_style
      text_font: MONTSERRAT_16
      text_color: 0xFFFFFF
      align: CENTER
      bg_opa: TRANSP

  widgets:
    - obj:
        id: main_panel
        x: 0
        y: 0
        width: 800
        height: 480
        bg_color: 0x000000
        border_width: 0
        scrollable: false
        scrollbar_mode: "OFF"
        overflow_visible: false
        widgets:
          - label:
              id: main_title
              styles: label_style
              width: 800
              height: 40
              align: TOP_MID
              text: !lambda 'return id(display_text);'
          
          # Color test pattern
          - obj:
              id: color_pattern
              width: 800
              height: 120
              align: TOP_MID
              y: 50
              scrollable: false
              scrollbar_mode: "OFF"
              widgets:
                # Red
                - obj:
                    styles: color_box_style
                    align: LEFT_MID
                    x: 5
                    bg_color: 0xFF0000
                    scrollable: false
                    scrollbar_mode: "OFF"
                    widgets:
                      - label:
                          styles: color_label_style
                          align: BOTTOM_MID
                          y: -10
                          text: "RED"
                # Green
                - obj:
                    styles: color_box_style
                    align: LEFT_MID
                    x: 135
                    bg_color: 0x00FF00
                    scrollable: false
                    scrollbar_mode: "OFF"
                    widgets:
                      - label:
                          styles: color_label_style
                          align: BOTTOM_MID
                          y: -10
                          text: "GREEN"
                # Blue
                - obj:
                    styles: color_box_style
                    align: LEFT_MID
                    x: 265
                    bg_color: 0x0000FF
                    scrollable: false
                    scrollbar_mode: "OFF"
                    widgets:
                      - label:
                          styles: color_label_style
                          align: BOTTOM_MID
                          y: -10
                          text: "BLUE"
                # Yellow
                - obj:
                    styles: color_box_style
                    align: LEFT_MID
                    x: 395
                    bg_color: 0xFFFF00
                    scrollable: false
                    scrollbar_mode: "OFF"
                    widgets:
                      - label:
                          styles: color_label_style
                          align: BOTTOM_MID
                          y: -10
                          text: "YELLOW"
                # Magenta
                - obj:
                    styles: color_box_style
                    align: LEFT_MID
                    x: 525
                    bg_color: 0xFF00FF
                    scrollable: false
                    scrollbar_mode: "OFF"
                    widgets:
                      - label:
                          styles: color_label_style
                          align: BOTTOM_MID
                          y: -10
                          text: "MAGENTA"
                # Cyan
                - obj:
                    styles: color_box_style
                    align: LEFT_MID
                    x: 655
                    bg_color: 0x00FFFF
                    scrollable: false
                    scrollbar_mode: "OFF"
                    widgets:
                      - label:
                          styles: color_label_style
                          align: BOTTOM_MID
                          y: -10
                          text: "CYAN"

          
          - label:
              id: counter_display
              styles: label_style
              width: 800
              height: 60
              align: CENTER
              text: !lambda 'return "Counter: " + std::to_string(id(counter));'
          
          # Rest of the configuration remains unchanged
          - label:
              id: touch_coords
              styles: button_label_style
              width: 800
              height: 30
              align: CENTER
              y: 200
              text: "Touch coordinates will appear here"
          
          - button:
              id: increment_btn
              width: 150
              height: 60
              align: BOTTOM_LEFT
              x: 100
              y: -50
              styles: button_style
              on_press:
                then:
                  - lambda: |-
                      id(counter)++;
                      lv_label_set_text(id(counter_display), ("Counter: " + std::to_string(id(counter))).c_str());
              widgets:
                - label:
                    styles: button_label_style
                    text: "+"
          
          - button:
              id: decrement_btn
              width: 150
              height: 60
              align: BOTTOM_RIGHT
              x: -100
              y: -50
              styles: button_style
              on_press:
                then:
                  - lambda: |-
                      id(counter)--;
                      lv_label_set_text(id(counter_display), ("Counter: " + std::to_string(id(counter))).c_str());
              widgets:
                - label:
                    styles: button_label_style
                    text: "-"
          
          - button:
              id: reset_btn
              width: 150
              height: 60
              align: BOTTOM_MID
              y: -50
              styles: button_style
              on_press:
                then:
                  - lambda: |-
                      id(counter) = 0;
                      id(display_text) = "Hello World!";
                      lv_label_set_text(id(counter_display), ("Counter: " + std::to_string(id(counter))).c_str());
              widgets:
                - label:
                    styles: button_label_style
                    text: "Reset"
